version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install uv
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Install dependencies
          command: |
            uv venv
            uv pip install autoflake isort
      - run:
          name: Check autoflake
          command: |
            source .venv/bin/activate
            autoflake --check --remove-all-unused-imports -r .
      - run:
          name: Check isort
          command: |
            source .venv/bin/activate
            isort --check-only .


workflows:
  version: 2
  linting:
    jobs:
      - lint
